/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prin;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelos.Admin;
import modelos.User;
import paneles.CambiaPanel;
import wbs.Wbs;
/**
 *
 * @author Leonidas
 */
public class pg_login extends javax.swing.JFrame {
    
    String name;
    final int   admon = 1,
                us = 2;
    int userType = admon;
    
    
    /**
     * Creates new form pg_login
     */
    public pg_login() {
        initComponents();
        pg_adminprin p = new pg_adminprin();
        
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            Logger.getLogger(pg_login.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JLabel();
        btn_manuales = new rojeru_san.RSButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnl_contenedor = new javax.swing.JPanel();
        pnl_login = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_ingresar = new rojeru_san.RSButton();
        lbl_mensajeerror = new javax.swing.JLabel();
        lbl_registrate = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        pnl_registrate = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_reguser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_regpass = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_regemail = new javax.swing.JTextField();
        btn_back = new javax.swing.JLabel();
        btn_registrate = new rojeru_san.RSButton();
        selAdmin = new javax.swing.JRadioButton();
        selUser = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(934, 481));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(47, 19, 6));
        jPanel1.setFocusable(false);
        jPanel1.setMinimumSize(new java.awt.Dimension(934, 481));
        jPanel1.setPreferredSize(new java.awt.Dimension(934, 481));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Close_Window_30px.png"))); // NOI18N
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, 30));

        btn_manuales.setBackground(new java.awt.Color(172, 95, 47));
        btn_manuales.setText("Manuales de usuario y de sistema");
        btn_manuales.setColorHover(new java.awt.Color(208, 124, 66));
        btn_manuales.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(btn_manuales, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, 300, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("¿Tienes alguna duda sobre este programa?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 350, 20));

        jPanel2.setBackground(new java.awt.Color(109, 80, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, 10, 440));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logo 3 (1).png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 510, 310));

        pnl_contenedor.setBackground(new java.awt.Color(47, 19, 6));
        pnl_contenedor.setLayout(new javax.swing.BoxLayout(pnl_contenedor, javax.swing.BoxLayout.LINE_AXIS));

        pnl_login.setBackground(new java.awt.Color(47, 19, 6));
        pnl_login.setMinimumSize(new java.awt.Dimension(320, 440));
        pnl_login.setPreferredSize(new java.awt.Dimension(320, 440));
        pnl_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Usuario");
        pnl_login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 80, 20));
        pnl_login.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 240, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Contraseña");
        pnl_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, 20));

        btn_ingresar.setBackground(new java.awt.Color(172, 95, 47));
        btn_ingresar.setText("Ingresar");
        btn_ingresar.setColorHover(new java.awt.Color(208, 124, 66));
        btn_ingresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        pnl_login.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 250, -1));

        lbl_mensajeerror.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        lbl_mensajeerror.setForeground(new java.awt.Color(255, 0, 0));
        pnl_login.add(lbl_mensajeerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, 20));

        lbl_registrate.setBackground(new java.awt.Color(255, 255, 255));
        lbl_registrate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbl_registrate.setForeground(new java.awt.Color(172, 95, 47));
        lbl_registrate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_registrate.setText("Regístrate");
        lbl_registrate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbl_registrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_registrateMouseClicked(evt);
            }
        });
        pnl_login.add(lbl_registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 80, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("¿No estas registrado?");
        pnl_login.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 200, 20));

        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_passKeyPressed(evt);
            }
        });
        pnl_login.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 240, 30));

        pnl_contenedor.add(pnl_login);

        pnl_registrate.setBackground(new java.awt.Color(47, 19, 6));
        pnl_registrate.setMinimumSize(new java.awt.Dimension(371, 440));
        pnl_registrate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText(" Usuario");
        pnl_registrate.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 20));
        pnl_registrate.add(txt_reguser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 240, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Contraseña");
        pnl_registrate.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 130, 20));

        txt_regpass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_regpassKeyPressed(evt);
            }
        });
        pnl_registrate.add(txt_regpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 240, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Email");
        pnl_registrate.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 130, 20));
        pnl_registrate.add(txt_regemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 240, 30));

        btn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Go_Back_24px.png"))); // NOI18N
        btn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_backMouseClicked(evt);
            }
        });
        pnl_registrate.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 30, 30));

        btn_registrate.setBackground(new java.awt.Color(172, 95, 47));
        btn_registrate.setText("Registrar");
        btn_registrate.setColorHover(new java.awt.Color(208, 124, 66));
        btn_registrate.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_registrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrateActionPerformed(evt);
            }
        });
        pnl_registrate.add(btn_registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 240, -1));

        buttonGroup1.add(selAdmin);
        selAdmin.setForeground(new java.awt.Color(255, 255, 255));
        selAdmin.setSelected(true);
        selAdmin.setText("Administrador");
        selAdmin.setOpaque(false);
        selAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selAdminMouseClicked(evt);
            }
        });
        pnl_registrate.add(selAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        buttonGroup1.add(selUser);
        selUser.setForeground(new java.awt.Color(255, 255, 255));
        selUser.setText("Usuario");
        selUser.setOpaque(false);
        selUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                selUserMouseClicked(evt);
            }
        });
        pnl_registrate.add(selUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        pnl_contenedor.add(pnl_registrate);

        jPanel1.add(pnl_contenedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 330, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_registrateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registrateMouseClicked
        pnl_registrate.setVisible(true);
        pnl_login.setVisible(false);
    }//GEN-LAST:event_lbl_registrateMouseClicked

    private void btn_registrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrateActionPerformed
        registrarse();
    }//GEN-LAST:event_btn_registrateActionPerformed

    private void btn_backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_backMouseClicked
        pnl_registrate.setVisible(false);
        pnl_login.setVisible(true);
    }//GEN-LAST:event_btn_backMouseClicked

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
         
        ingresar();
        
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void registrarse()
    {
        if (txt_reguser.getText().isEmpty() || txt_regpass.getText().isEmpty() || txt_regemail.getText().isEmpty()) 
        {
             JOptionPane.showMessageDialog(this, "Por favor llene todos los campos de registro", "Parametros vacios", JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try
            {
                if (wbs.isInFile(txt_reguser.getText(),"usuarios.txt")) 
                {
                    JOptionPane.showMessageDialog(null,"Este usuario ya se encuentra registrado");
                }
                else
                {
                    if (wbs.welcomeMail(txt_regemail.getText(),txt_reguser.getText())) 
                    {
                        wbs.addToFile(txt_reguser.getText()+","+txt_regpass.getText()+","+txt_regemail.getText()+","+userType+",", "usuarios.txt");
                        JOptionPane.showMessageDialog(null,"Registro exitoso");
                        File c = new File("allusers/"+txt_reguser.getText());
                        if (c.mkdir()) 
                        {System.out.println("creado");}
                        else
                        {System.out.println("error de creación de directorio");}
                        pnl_registrate.setVisible(false);
                        pnl_login.setVisible(true);
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Por favor ingrese un correo válido", "Correo inválido", JOptionPane.ERROR_MESSAGE);
                    }
                }    
            }
            catch(IOException ioe)
            {
                System.out.println("error de archivo");
                JOptionPane.showMessageDialog(null,"no fue posible realizar el registro");
                ioe.printStackTrace();
            }
            catch(NullPointerException npe)
            {
                System.out.println("parametros faltantes");
                npe.printStackTrace();
                JOptionPane.showMessageDialog(this, "Por favor llene todos los campos de registro", "Parametros vacios", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }
    
    private void ingresar()
    {
        if (txt_user.getText().isEmpty() || txt_pass.getText().isEmpty()) {
             //USE GET TEXT PARA UN PASSWORD, PERDONAME LA VIDA DEPUES LO CAMBIO.
             //yo tampoco tengo ni idea de como cambiarlo, el paswordField lo cifra
            lbl_mensajeerror.setText("Debe llenar los dos campos");
        } else {
            String words = txt_user.getText() + "," + txt_pass.getText();
            System.out.println("Words: "+words);
            String line = "";
            boolean mensajeerror = false;
            BufferedReader reader = null;
             try {
                 int size;
                 String palabras[];
                 reader = new BufferedReader(new FileReader("usuarios.txt"));
                  while ((line = reader.readLine()) != null) {
                      palabras = substr(line, 3);
                    if (palabras[0].equals(txt_user.getText()) && palabras[1].equals(txt_pass.getText())) {
                        size = line.length();
                        System.out.println("Line: " + line);
                        char dig = line.charAt(size - 2);
                        System.out.println("Dig: " + dig);
                        name = txt_user.getText();
                        if (dig == '2') {
                            mensajeerror = true;
                            new pg_ComunUser().setVisible(true);
                            Wbs.user = new User(name);
                            this.dispose();
                        } else if (dig == '1') {
                            mensajeerror = true;
                            pg_userprin admp = new pg_userprin();
                            admp.setVisible(true);
                            admp.setNombre(name);
                            Wbs.admin = new Admin(name);
                            Wbs.user = new User(name);
                            this.dispose();
                    }
//                    if (line.indexOf(words) > -1) {  
//                      
//                        }
                        
                    }
                  }
             if (mensajeerror == false) {
                JOptionPane.showMessageDialog(this, "Datos incorrectos", "Error", JOptionPane.ERROR_MESSAGE);
                txt_user.setText("");
                txt_pass.setText("");
            }
             } catch (FileNotFoundException ex) {
                 
                 System.out.println("archivo de usuarios no encontrado");
                 ex.printStackTrace();
                 
             } catch (IOException ex) {
                 System.out.println("error en la ejecuciòn del stream");
                 ex.printStackTrace();
             }
           
        }
    }
    private String[] substr(String line, int comas) {
        int ant = 0, p = 0, contguion = 0;
        String[] palabras = new String[100];
        for (int j = 0; j < line.length() - 1; j++) {
            if (line.charAt(j) == ',') {
                if (comas == 0) {
                    palabras[0] = line.substring(0, j);
                    ant = j + 1;
                    contguion++;

                    p++;

                } else {
                    if (contguion < comas) {
                        palabras[p] = line.substring(ant, j);
                        ant = j + 1;

                        p++;
                        contguion++;

                    }

                }
            }
            if (contguion == comas) {
                palabras[p] = line.substring(ant, line.length() - 1);

                p++;
                contguion++;
            }
        }
        return palabras;
    }
    private void btn_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_cerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarMouseClicked

    private void selAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selAdminMouseClicked
        
        if (selAdmin.isSelected()) 
        {
            userType = admon;
        }
        
    }//GEN-LAST:event_selAdminMouseClicked

    private void selUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selUserMouseClicked
        
        if (selUser.isSelected()) 
        {
            userType = us;
        }
        
    }//GEN-LAST:event_selUserMouseClicked

    private void txt_regpassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_regpassKeyPressed
        if (evt.getKeyCode() == 10) 
        {
            registrarse();
        }
    }//GEN-LAST:event_txt_regpassKeyPressed

    private void txt_passKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyPressed
        
        if (evt.getKeyCode() == 10) 
        {
            ingresar();
        }
        
    }//GEN-LAST:event_txt_passKeyPressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        
        this.setLocation(evt.getXOnScreen()-xin,evt.getYOnScreen()-yin);
        
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        xin=evt.getX();
        yin=evt.getY();
    }//GEN-LAST:event_formMousePressed

    int xin,yin;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pg_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pg_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pg_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pg_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pg_login().setVisible(true);
            }
        });
    }

    
    private Wbs wbs = new Wbs();
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn_back;
    private javax.swing.JLabel btn_cerrar;
    private rojeru_san.RSButton btn_ingresar;
    private rojeru_san.RSButton btn_manuales;
    private rojeru_san.RSButton btn_registrate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_mensajeerror;
    private javax.swing.JLabel lbl_registrate;
    private javax.swing.JPanel pnl_contenedor;
    private javax.swing.JPanel pnl_login;
    private javax.swing.JPanel pnl_registrate;
    private javax.swing.JRadioButton selAdmin;
    private javax.swing.JRadioButton selUser;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_regemail;
    private javax.swing.JTextField txt_regpass;
    private javax.swing.JTextField txt_reguser;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
