/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author Leonidas
 */
public class pnl_calendario extends javax.swing.JPanel {

    /**
     * Creates new form pnl_calendario
     */
    public pnl_calendario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSCalendar1 = new rojeru_san.componentes.RSCalendar();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(650, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSCalendar1.setBackground(new java.awt.Color(245, 246, 212));
        rSCalendar1.setAltoFilas(50);
        rSCalendar1.setAutoscrolls(true);
        rSCalendar1.setColorBackground(new java.awt.Color(133, 219, 24));
        rSCalendar1.setColorButtonHover(new java.awt.Color(167, 197, 32));
        rSCalendar1.setColorDiaActual(new java.awt.Color(205, 232, 85));
        add(rSCalendar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 500));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSCalendar rSCalendar1;
    // End of variables declaration//GEN-END:variables
}
