/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paneles;

/**
 *
 * @author Leonidas
 */
public class pnl_admcronograma extends javax.swing.JPanel {

    /**
     * Creates new form pnl_admcronograma
     */
    public pnl_admcronograma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rSCalendar1 = new rojeru_san.componentes.RSCalendar();

        setBackground(new java.awt.Color(218, 175, 118));
        setMinimumSize(new java.awt.Dimension(689, 521));

        rSCalendar1.setBackground(new java.awt.Color(245, 246, 212));
        rSCalendar1.setAltoFilas(50);
        rSCalendar1.setAutoscrolls(true);
        rSCalendar1.setColorBackground(new java.awt.Color(133, 219, 24));
        rSCalendar1.setColorButtonHover(new java.awt.Color(167, 197, 32));
        rSCalendar1.setColorDiaActual(new java.awt.Color(205, 232, 85));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSCalendar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(rSCalendar1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.componentes.RSCalendar rSCalendar1;
    // End of variables declaration//GEN-END:variables
}
